name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Get code from GitHub
        uses: actions/checkout@v4

      - name: Step 2 - Check project files
        run: ls

      - name: Step 3 - Build step
        run: echo "Build completed successfully"

      - name: Step 4 - Deployment step
        run: echo "Application deployed successfully"
